### ISSUE TITLE
ibus-pinyin 1.5.0 on debian 9 will hide terminal cursor

### ISSUE THREAD

**Issue by chengweiv5** [phuang/ibus-pinyin#11]
After upgrade my debian 8 to 9 I found that ibus-pinyin 1.5.0 will hide terminal cursor once it input any chinese words, it works fine in debian 8.

And the terminal curosr will come back once I have switched to ibus english, so it seems ibus pinyin 1.5.0 has some problems with terminal(gnome-terminal and terminator)

How to reproduce this issue?

1. open a terminal(gnome-terminal or terminator) and keep ibus in english mode, the terminal show cursor as expected
2. press ctrl-space keybinding to switch ibus to ibus-pinyin, the terminal still show cursor as expected
3. type any chinese word into terminal, **now the cursor disappear**
4. press ctrl-space keybinding to switch back to ibus english, the terminal corsor comes back

This issue is not only happens in a terminal console but also in VIM.

BTW, I found that SunPinyin works fine.

**Comment by chengweiv5** [comment]
any update?

**Comment by chengweiv5** [comment]
It seems not a bug of ibus nor ibus-pinyin because I installed the versions of ibus and ibus-pinyin in debian 8's repo, it doesn't work either.

**Comment by ghost** [comment]
Recently, I also encountered this problem.  I solved this problem by  unchecking the item 『Embed preedit text in application window』in the ibus preferences (run ibus-setup from the terminal.

**Comment by chengweiv5** [comment]
> Recently, I also encountered this problem. I solved this problem by unchecking the item 『Embed preedit text in application window』in the ibus preferences (run ibus-setup from the terminal.

Great, it works for me!

**Comment by ghost** [comment]
> > Recently, I also encountered this problem. I solved this problem by unchecking the item 『Embed preedit text in application window'in the ibus preferences (run ibus-setup from the terminal.
> 
> Great, it works for me!

Some more words: I accidently knew that ibus-pinyin is not maintained anymore and there is a replacement called ibus-libpinyin.
